### ISSUE TITLE
Wondering about why the container

### ISSUE THREAD

**Issue by yajo** [TyberiusPrime/anysnake2#1]
I'm not saying it's good or bad, it's just that I find it strange, as theoretically we should be able to get the same level of reproducibility with just a derivation.

I'm just curious, I hope you don't mind. 😃

**Comment by TyberiusPrime** [comment]
Well the big thing for our use case is that we need the filesystem namespace / bind  mounts .

One part is that the editable python needs them to avoid having to rewrite stuff (if the project folder get's moved that is). We rely heavily on editable installs to actually do our work ;).

And then we use it to make sure our projects don't touch anything outside their defined paths / never have a chance to write down a path that's dependent on where they're stored.

And the last part is that we anticipate having to run our stuff on a 'cluster' that essentially schedules random container images for execution. But to do that you need to build a 'real image' with 'anysnake build sif' which isn't just a symlink forest.

So it is an excellent question!

(note that there's also 'anysnake2 develop' which get's you a shell with an adjusted PATH, PYTHONPATH and R_LIB_SITE, without the container. 
The editable pythons should be importable there. But it's a path much less traveled).

**Comment by yajo** [comment]
Ahthanks, it's clearer now!
